# -------------------------------------------------------------------
# Giec Taxonomies
# -------------------------------------------------------------------
#
#
#   Author : PLIQUE Guillaume
#   Organization : Medialab - Sciences Po
#   Version : 1.0

module Taxonomies

	# Authors Groups
	Groups = [
		{:symbol => 'AG', :name => 'African Group', :type => 'GEO'},
		{:symbol => 'APG', :name => 'Asian-Pacific Group', :type => 'GEO'},
		{:symbol => 'GRULAC', :name => 'Latin American and Caribbean Group', :type => 'GEO'},
		{:symbol => 'EEG', :name => 'Eastern European Group', :type => 'GEO'},
		{:symbol => 'WEOG', :name => 'Western Europe and Other States Group', :type => 'GEO'},
		{:symbol => 'DdC', :name => 'Developed Countries', :type => 'ECO'},
		{:symbol => 'EiT', :name => 'Economies in Transition', :type => 'ECO'},
		{:symbol => 'DgE', :name => 'Developing Economies', :type => 'ECO'},
		{:symbol => 'OCDE', :name => 'OECD', :type => 'ECO'},
		{:symbol => 'BRICS', :name => 'BRICS', :type => 'ECO'},
		{:symbol => 'G8', :name => 'G8', :type => 'ECO'},
		{:symbol => 'G20', :name => 'G20', :type => 'ECO'},
		{:symbol => 'G77', :name => 'G77', :type => 'ECO'},
		{:symbol => 'AOGCM', :name => 'Countries with Coupled Atmosphere-Ocean Global Climate Models', :type => 'CLI'},
		{:symbol => 'A1', :name => 'Annex I', :type => 'CLI'},
		{:symbol => 'NA1', :name => 'Non-Annex I', :type => 'CLI'},
		{:symbol => 'LCDs', :name => 'Least Developed Countries', :type => 'CLI'},
		{:symbol => 'AOSIS', :name => 'Alliance of Small Island States', :type => 'CLI'},
		{:symbol => 'EU', :name => 'European Union', :type => 'CLI'},
		{:symbol => 'UG', :name => 'Umbrella Group', :type => 'CLI'},
		{:symbol => 'CfRN', :name => 'Coalition of Rainforest Nations', :type => 'CLI'},
		{:symbol => 'CACAM', :name => 'Central Asia, Caucasus and Moldova', :type => 'CLI'},
		{:symbol => 'OPEC', :name => 'Organization of the Petroleum Exporting Countries', :type => 'CLI'},
		{:symbol => 'LAS', :name => 'League of Arab States', :type => 'CLI'},
		{:symbol => 'EiG', :name => 'Environmental Integrity Group', :type => 'CLI'},
		{:symbol => 'AILAC', :name => 'Alliance of Latin America and the Caribbean', :type => 'CLI'},
		{:symbol => 'ALBA', :name => 'Bolivarian Alliance for the Peoples of our America', :type => 'CLI'},
		{:symbol => 'OIF', :name => 'Organisation Internationale de la Francophonie', :type => 'CLI'}
	]

	# Institution Types
	InstitutionTypes = [
		{:symbol => 'AS', :name => 'Academy of Science'},
		{:symbol => 'COMP', :name => 'Company'},
		{:symbol => 'CONS', :name => 'Consultants'},
		{:symbol => 'FND', :name => 'Foundation'},
		{:symbol => 'GA', :name => 'Government Agency'},
		{:symbol => 'HEI', :name => 'Higher Education Institution'},
		{:symbol => 'INDV', :name => 'Individual'},
		{:symbol => 'INT', :name => 'International Institution'},
		{:symbol => 'NGO', :name => 'Non-Governmental Organization'},
		{:symbol => 'OTHER', :name => 'Other'},
		{:symbol => 'PRO', :name => 'Public Research Organisation'}
	]

	# Roles
	Roles = [
		{:symbol => 'LA', :name => 'Lead Author'},
		{:symbol => 'LCA', :name => 'Coordinating Lead Author'},
		{:symbol => 'RE', :name => 'Review Editor'},
		{:symbol => 'CA', :name => 'Contributing Author'}
	]

	# Assessment Reports
	AssessmentReports = [
		{:year => '1990'},
		{:year => '1995'},
		{:year => '2001'},
		{:year => '2007'},
		{:year => '2013'}
	]

	# Chapter Types
	ChapterTypes = [
		{:symbol => 'GHG', :name => 'Greenhouse Gases'},
		{:symbol => 'AER', :name => 'Aerosols'},
		{:symbol => 'RAD', :name => 'Radiative Forcing'},
		{:symbol => 'CLI', :name => 'Climate Processes'},
		{:symbol => 'MOD', :name => 'Model Evaluation'},
		{:symbol => 'EQU', :name => 'Equilibrium Climate Change'},
		{:symbol => 'PRO', :name => 'Projections of Global Climate Change'},
		{:symbol => 'OBS', :name => 'Observate Climate Variability'},
		{:symbol => 'DET', :name => 'Detection and Attribution'},
		{:symbol => 'SEA', :name => 'Sea Level Change'},
		{:symbol => 'EFF', :name => 'Effects on Ecosystems'},
		{:symbol => 'ADV', :name => 'Advancing Understanding'},
		{:symbol => 'OVE', :name => 'Climate System: Overview'},
		{:symbol => 'RAD', :name => 'Radiative Forcing'},
		{:symbol => 'CAR', :name => 'Carbon Cycle and Biogeochemistry'},
		{:symbol => 'ATM', :name => 'Atmosphere and Surface'},
		{:symbol => 'REG', :name => 'Regional Downscaling'},
		{:symbol => 'SCE', :name => 'Scenario Development'},
		{:symbol => 'HIS', :name => 'History of Climate Change: Overview'},
		{:symbol => 'CRY', :name => 'Cryosphere'},
		{:symbol => 'OCE', :name => 'Oceans'},
		{:symbol => 'PAL', :name => 'Paleoclimate'},
		{:symbol => 'INT', :name => 'Introduction'},
	]

	# Countries
	Countries = [
		{:name => "Albania", :groupings => "EEG/EiT/NA1/OIF"},
		{:name => "Algeria", :groupings => "AG/DgE/G77/NA1/OPEC/LAS"},
		{:name => "Antigua", :groupings => "GRULAC/DgE/G77/NA1/AOSIS/ALBA"},
		{:name => "Argentina", :groupings => "GRULAC/DgE/G20/G77/NA1/CfRN"},
		{:name => "Australia", :groupings => "WEOG/DdC/OCDE/G20/AOGCM/A1/UG"},
		{:name => "Austria", :groupings => "WEOG/DdC/OCDE/A1/EU"},
		{:name => "Bangladesh", :groupings => "APG/DgE/G77/NA1/LDCs/CfRN"},
		{:name => "Barbados", :groupings => "GRULAC/DgE/G77/NA1/AOSIS"},
		{:name => "Belgium", :groupings => "WEOG/DdC/OCDE/A1/EU/OIF"},
		{:name => "Belize", :groupings => "GRULAC/G77/NA1/AOSIS/CfRN"},
		{:name => "Benin", :groupings => "AG/G77/NA1/LDCs/OIF"},
		{:name => "Bolivia", :groupings => "GRULAC/DgE/G77/NA1/ALBA"},
		{:name => "Botswana", :groupings => "AG/DgE/G77/NA1"},
		{:name => "Brazil", :groupings => "GRULAC/DgE/BRICS/G20/G77/NA1"},
		{:name => "Bulgaria", :groupings => "EEG/DdC/A1/EU/OIF"},
		{:name => "Cambodia", :groupings => "APG/G77/NA1/LDCs/OIF"},
		{:name => "Canada", :groupings => "WEOG/DdC/OCDE/G8/G20/AOGCM/A1/UG/OIF"},
		{:name => "Chad", :groupings => "AG/DgE/G77/NA1/LDCs/OIF"},
		{:name => "Chile", :groupings => "GRULAC/DgE/OCDE/G77/NA1/CfRN/AILAC"},
		{:name => "China", :groupings => "APG/DgE/BRICS/G20/G77/AOGCM/NA1"},
		{:name => "Colombia", :groupings => "GRULAC/DgE/G77/NA1/AILAC"},
		{:name => "Costa Rica", :groupings => "GRULAC/DgE/G77/NA1/CfRN/AILAC"},
		{:name => "Cuba", :groupings => "GRULAC/DgE/G77/NA1/AOSIS/ALBA"},
		{:name => "Czech Republic", :groupings => "EEG/DdC/OCDE/A1/EU"},
		{:name => "Denmark", :groupings => "WEOG/DdC/OCDE/A1/EU"},
		{:name => "Ecuador", :groupings => "GRULAC/DgE/G77/NA1/CfRN/OPEC/ALBA"},
		{:name => "Egypt", :groupings => "AG/DgE/G77/NA1/LAS/OIF"},
		{:name => "El Salvador", :groupings => "GRULAC/DgE/G77/NA1/CfRN"},
		{:name => "Ethiopia", :groupings => "AG/DgE/G77/NA1/LDCs"},
		{:name => "Fiji", :groupings => "APG/G77/NA1/AOSIS/CfRN"},
		{:name => "Finland", :groupings => "WEOG/DdC/OCDE/A1/EU"},
		{:name => "France", :groupings => "WEOG/DdC/OCDE/G8/G20/AOGCM/A1/EU/OIF"},
		{:name => "Germany", :groupings => "WEOG/DdC/OCDE/G8/G20/AOGCM/A1/EU"},
		{:name => "Ghana", :groupings => "AG/DgE/G77/NA1/CfRN/OIF"},
		{:name => "Greece", :groupings => "WEOG/DdC/OCDE/A1/EU/OIF"},
		{:name => "Guatemala", :groupings => "GRULAC/DgE/G77/NA1/CfRN/AILAC"},
		{:name => "Guinea", :groupings => "AG/DgE/G77/NA1/LDCs/OIF"},
		{:name => "Hong Kong", :groupings => "APG/DgE"},
		{:name => "Hungary", :groupings => "EEG/DdC/OCDE/A1/EU"},
		{:name => "Iceland", :groupings => "WEOG/DdC/OCDE/A1/UG"},
		{:name => "India", :groupings => "APG/DgE/BRICS/G20/G77/NA1"},
		{:name => "Indonesia", :groupings => "APG/DgE/G20/G77/NA1/CfRN"},
		{:name => "Iran", :groupings => "APG/DgE/G77/NA1/OPEC"},
		{:name => "Ireland", :groupings => "WEOG/DdC/OCDE/A1/EU"},
		{:name => "Israel", :groupings => "WEOG/DgE/OCDE/NA1"},
		{:name => "Italy", :groupings => "WEOG/DdC/OCDE/G8/G20/A1/EU"},
		{:name => "Jamaica", :groupings => "GRULAC/DgE/G77/NA1/AOSIS"},
		{:name => "Japan", :groupings => "APG/DdC/OCDE/G8/G20/AOGCM/A1/UG"},
		{:name => "Kazakhstan", :groupings => "APG/EiT/NA1/CACAM"},
		{:name => "Kenya", :groupings => "AG/DgE/G77/NA1/CfRN"},
		{:name => "Kiribati", :groupings => "NA1/LDCs/AOSIS"},
		{:name => "Kuwait", :groupings => "APG/DgE/G77/NA1/OPEC/LAS"},
		{:name => "Laos", :groupings => "APG/G77/NA1/LDCs/OIF"},
		{:name => "Lithuania", :groupings => "EEG/DdC/A1/EU"},
		{:name => "Madagascar", :groupings => "AG/DgE/G77/NA1/LDCs/CfRN/OIF"},
		{:name => "Malawi", :groupings => "AG/DgE/G77/NA1/LDCs"},
		{:name => "Malaysia", :groupings => "APG/DgE/G77/NA1/CfRN"},
		{:name => "Maldives", :groupings => "APG/G77/NA1/AOSIS"},
		{:name => "Malta", :groupings => "WEOG/DdC/A1/AOSIS/EU"},
		{:name => "Mauritius", :groupings => "AG/DgE/G77/NA1/AOSIS/OIF"},
		{:name => "Mexico", :groupings => "GRULAC/DgE/OCDE/G20/NA1/EIG"},
		{:name => "Moldova", :groupings => "EEG/EiT/NA1/CACAM/OIF"},
		{:name => "Monaco", :groupings => "WEOG/A1/EIG/OIF"},
		{:name => "Mongolia", :groupings => "APG/G77/NA1"},
		{:name => "Morocco", :groupings => "AG/DgE/G77/NA1/LAS/OIF"},
		{:name => "Mozambique", :groupings => "AG/DgE/G77/NA1/LDCs"},
		{:name => "Namibia", :groupings => "AG/DgE/G77/NA1"},
		{:name => "Nepal", :groupings => "APG/DgE/G77/NA1/LDCs"},
		{:name => "New Zealand", :groupings => "WEOG/DdC/OCDE/A1/UG"},
		{:name => "Nigeria", :groupings => "AG/DgE/G77/NA1/CfRN/OPEC"},
		{:name => "Norway", :groupings => "WEOG/DdC/OCDE/AOGCM/A1/UG"},
		{:name => "Oman", :groupings => "APG/DgE/G77/NA1/LAS"},
		{:name => "Pakistan", :groupings => "APG/DgE/G77/NA1/CfRN"},
		{:name => "Papua New Guinea", :groupings => "APG/DgE/G77/NA1/CfRN"},
		{:name => "Peru", :groupings => "GRULAC/DgE/G77/NA1/AILAC"},
		{:name => "Philippines", :groupings => "APG/DgE/G77/NA1"},
		{:name => "Poland", :groupings => "EEG/DdC/OCDE/A1/EU"},
		{:name => "Portugal", :groupings => "WEOG/DdC/OCDE/A1/EU"},
		{:name => "Puerto Rico", :groupings => "AOSIS"},
		{:name => "Romania", :groupings => "EEG/DdC/A1/EU/OIF"},
		{:name => "Russian Federation", :groupings => "EEG/EiT/BRICS/G8/G20/AOGCM/A1/UG"},
		{:name => "Samoa", :groupings => "APG/G77/NA1/LDCs/AOSIS/CfRN"},
		{:name => "Saudi Arabia", :groupings => "APG/DgE/G20/G77/NA1/OPEC/LAS"},
		{:name => "Senegal", :groupings => "AG/DgE/G77/NA1/LDCs/OIF"},
		{:name => "Seychelles", :groupings => "AG/G77/NA1/AOSIS/OIF"},
		{:name => "Sierra Leone", :groupings => "AG/DgE/G77/NA1/LDCs/CfRN"},
		{:name => "Singapore", :groupings => "APG/DgE/G77/NA1/AOSIS"},
		{:name => "Slovakia", :groupings => "EEG/DdC/OCDE/A1/EU"},
		{:name => "Slovenia", :groupings => "EEG/DdC/OCDE/A1/EU"},
		{:name => "South Africa", :groupings => "AG/DgE/BRICS/G20/G77/NA1"},
		{:name => "South Korea", :groupings => "APG/DgE/OCDE/G20/AOGCM/NA1/EIG"},
		{:name => "Spain", :groupings => "WEOG/DdC/OCDE/A1/EU"},
		{:name => "Sri Lanka", :groupings => "APG/DgE/G77/NA1"},
		{:name => "Sudan", :groupings => "AG/DgE/G77/NA1/LDCs/LAS"},
		{:name => "Sweden", :groupings => "WEOG/DdC/OCDE/A1/EU"},
		{:name => "Switzerland", :groupings => "WEOG/DdC/OCDE/A1/EIG/OIF"},
		{:name => "Taiwan", :groupings => "DgE"},
		{:name => "Tanzania", :groupings => "AG/DgE/G77/NA1/LDCs"},
		{:name => "Thailand", :groupings => "APG/DdC/G77/NA1/CfRN"},
		{:name => "The Gambia", :groupings => "AG/DgE/G77/NA1/LDCs"},
		{:name => "The Netherlands", :groupings => "WEOG/DdC/OCDE/A1/AOSIS/EU"},
		{:name => "Togo", :groupings => "AG/DgE/G77/NA1/LDCs/OIF"},
		{:name => "Trinidad and Tobago", :groupings => "GRULAC/DgE/G77/NA1/AOSIS"},
		{:name => "Tunisia", :groupings => "AG/DgE/G77/NA1/LAS/OIF"},
		{:name => "Turkey", :groupings => "WEOG/DgE/OCDE/G20/A1"},
		{:name => "Turkmenistan", :groupings => "APG/EiT/G77/NA1/CACAM"},
		{:name => "USA", :groupings => "WEOG/DdC/OCDE/G8/G20/AOGCM/A1/UG"},
		{:name => "USSR", :groupings => "EEG/EiT/BRICS/G8/G20/AOGCM/A1/UG"},
		{:name => "Uganda", :groupings => "AG/DgE/G77/NA1/LDCs/CfRN"},
		{:name => "Ukraine", :groupings => "EEG/EiT/A1/UG"},
		{:name => "United Kingdom", :groupings => "WEOG/DdC/OCDE/G8/G20/AOGCM/A1/EU"},
		{:name => "Uruguay", :groupings => "GRULAC/DgE/G77/NA1/CfRN"},
		{:name => "Uzbekistan", :groupings => "APG/EiT/NA1/CACAM"},
		{:name => "Venezuela", :groupings => "GRULAC/DgE/G77/NA1/OPEC/AILAC"},
		{:name => "Vietnam", :groupings => "APG/DgE/G77/NA1/CfRN/OIF"},
		{:name => "Zambia", :groupings => "AG/DgE/G77/NA1/LDCs"},
		{:name => "Zimbabwe", :groupings => "AG/DgE/G77/NA1"}
	]
end