#!/bin/bash

# Total queries
echo "Computing Axis 0..."
ruby query.rb axis0

echo "Computing Axis 1..."
ruby query.rb axis1

echo "Computing Axis 2..."
ruby query.rb axis2

echo "Computing Ianzilla..."
ruby query.rb ianzilla

echo "Computing Inner Circle..."
ruby query.rb inner_circle

echo "Computing Misc..."
ruby query.rb misc

echo "Computing Participations..."
ruby query.rb participations

echo "Computing Potatoes.."
ruby query.rb potatoes

echo "Done !"
